[build-system]
requires = ["setuptools >= 64", "wheel"]
build-backend = "setuptools.build_meta"



[project]
name = "alpine"
version = "1.0.0"
description = "A pytorch library for implicit neural representations"
authors = [{ name = "Kushal Vyas", email="kushalkvyas@gmail.com" }]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.21",
    
]

[project.urls]
Homepage = "https://github.com/kushalvyas/alpine"


[tool.setuptools.packages.find]
where = ["./alpine/"]  

[tool.setuptools]
package-dir = {"" = "./alpine"}